name: Build Vite app with LaTeX prebuild

on:
    workflow_dispatch:
    push:
        branches:
            - main
        paths: 
            - content/**/*.tex
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm' 

      # - name: Install LaTeX (pdflatex, etc.)
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install -y \
      #       texlive-latex-recommended \
      #       texlive-latex-extra \
      #       texlive-fonts-recommended
      
      - name: Install dependencies
        run: npm ci

      - name: Run prebuild (pdflatex / lwarp / etc.)
        run: npm run prebuild

  #     - name: Build Vite app
  #       run: npm run build

  #     - name: Upload built app as artifact
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: vite-dist
  #         path: artifact

  # use-artifact:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Download built app
  #       uses: actions/download-artifact@v4
  #       with:
  #         name: vite-dist
  #         path: dist
  #     - run: ls -R dist
